import type { ChecklistItem } from './types';

export const PRISMA_CHECKLIST: Omit<ChecklistItem, 'status' | 'note'>[] = [
  { number: 1,  section: 'TITLE',        item: 'Title',                    description: 'Identify the report as a systematic review.' },
  { number: 2,  section: 'ABSTRACT',     item: 'Abstract',                 description: 'Provide a structured abstract including background, objectives, data sources, eligibility, appraisal, synthesis, results, limitations, and conclusions.' },
  { number: 3,  section: 'INTRODUCTION', item: 'Rationale',                description: 'Describe the rationale for the review in the context of existing knowledge.' },
  { number: 4,  section: 'INTRODUCTION', item: 'Objectives',               description: 'Provide an explicit statement of the objective(s) or question(s) the review addresses.' },
  { number: 5,  section: 'METHODS',      item: 'Eligibility criteria',     description: 'Specify the inclusion and exclusion criteria for the review.' },
  { number: 6,  section: 'METHODS',      item: 'Information sources',      description: 'Specify all databases, registers, websites, and other sources searched with dates.' },
  { number: 7,  section: 'METHODS',      item: 'Search strategy',          description: 'Present the full search strategies for all databases including filters applied.' },
  { number: 8,  section: 'METHODS',      item: 'Selection process',        description: 'Specify methods for selecting studies, including number of reviewers and disagreement resolution.' },
  { number: 9,  section: 'METHODS',      item: 'Data collection process',  description: 'Specify methods for extracting data from reports.' },
  { number: 10, section: 'METHODS',      item: 'Data items',               description: 'List and define all outcomes, exposures, covariates, and data sought.' },
  { number: 11, section: 'METHODS',      item: 'Study risk of bias',       description: 'Specify methods for assessing risk of bias in included studies.' },
  { number: 12, section: 'METHODS',      item: 'Effect measures',          description: 'Specify the effect measure(s) used in the synthesis.' },
  { number: 13, section: 'METHODS',      item: 'Synthesis methods',        description: 'Describe the planned approach to synthesis.' },
  { number: 14, section: 'METHODS',      item: 'Reporting bias',           description: 'Describe methods for assessing reporting biases.' },
  { number: 15, section: 'METHODS',      item: 'Certainty assessment',     description: 'Describe methods for assessing certainty or confidence in the body of evidence.' },
  { number: 16, section: 'RESULTS',      item: 'Study selection',          description: 'Describe results of search and selection process including PRISMA flow diagram.' },
  { number: 17, section: 'RESULTS',      item: 'Study characteristics',    description: 'Cite each included study and present its characteristics.' },
  { number: 18, section: 'RESULTS',      item: 'Risk of bias in studies',  description: 'Present assessments of risk of bias for each included study.' },
  { number: 19, section: 'RESULTS',      item: 'Results of studies',       description: 'For all outcomes, present results of included studies.' },
  { number: 20, section: 'RESULTS',      item: 'Results of syntheses',     description: 'For each synthesis, present results in full.' },
  { number: 21, section: 'RESULTS',      item: 'Reporting biases',         description: 'Present assessments of reporting biases.' },
  { number: 22, section: 'RESULTS',      item: 'Certainty of evidence',    description: 'Present assessments of certainty of evidence.' },
  { number: 23, section: 'DISCUSSION',   item: 'Discussion',               description: 'Provide a general interpretation of the results in context of other evidence.' },
  { number: 24, section: 'DISCUSSION',   item: 'Limitations of evidence',  description: 'Discuss limitations of included evidence.' },
  { number: 25, section: 'DISCUSSION',   item: 'Limitations of process',   description: 'Discuss limitations of review process.' },
  { number: 26, section: 'DISCUSSION',   item: 'Conclusions',              description: 'Provide a general interpretation and implications for practice and research.' },
  { number: 27, section: 'OTHER',        item: 'Funding',                  description: 'Provide information on funding for the review.' },
];
